# Generated by Django 4.1.7 on 2023-03-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_articlei̇mage_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articleİmage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Makaleye Fotograf ekleyin'),
        ),
    ]
